export const ClearDilDocumentType = {
  PASSPORT: "PASSPORT",
  DRIVING_LICENCE: "DRIVING_LICENCE",
  NATIONAL_IDENTITY_CARD: "NATIONAL_IDENTITY_CARD",
  RESIDENCE_PERMIT: "RESIDENCE_PERMIT",
  VISA: "VISA",
  WORK_PERMIT: "WORK_PERMIT",
  GENERIC: "GENERIC",
};

export const ClearDilCaptureType = {
  PHOTO: "PHOTO",
  VIDEO: "VIDEO"
}




